+ etc

+ etc/acme-sh
+ etc/acme-sh/**

+ etc/apache2
+ etc/apache2/**

+ etc/backup
+ etc/backup/**

+ etc/bind
+ etc/bind/**

+ etc/cron.d
+ etc/cron.d/**

+ etc/dbbackup.conf

+ etc/dovecot
+ etc/dovecot/**

+ etc/fail2ban
+ etc/fail2ban/**

+ etc/firewall
+ etc/firewall/**

+ etc/libvirt
+ etc/libvirt/**

+ etc/logrotate.d
+ etc/logrotate.d/**

+ etc/minidlna.conf

+ etc/netplan
+ etc/netplan/**

+ etc/nullmailer
+ etc/nullmailer/**

+ etc/php
+ etc/php/**

+ etc/postfix
+ etc/postfix/**

+ etc/postgresql
+ etc/postgresql/**

+ etc/pure-ftpd
+ etc/pure-ftpd/**

+ etc/redis
+ etc/redis/**

+ etc/report.conf

+ etc/rspamd
+ etc/rspamd/**

+ etc/rsyslog.conf
+ etc/rsyslog.d
+ etc/rsyslog.d/**

+ etc/samba
+ etc/samba/**

+ etc/zabbix
+ etc/zabbix/**

+ opt
+ opt/**

+ srv

+ srv/cloud
+ srv/cloud/**

+ srv/mail
+ srv/mail/**

+ srv/pgbackup
+ srv/pgbackup/**

+ srv/share
+ srv/share/**

+ usr
+ usr/share

+ usr/share/nextcloud
+ usr/share/nextcloud/config
+ usr/share/nextcloud/config/config.php

+ usr/share/roundcube
+ usr/share/roundcube/config
+ usr/share/roundcube/config/config.inc.php
+ usr/share/roundcube/plugins
+ usr/share/roundcube/plugins/password
+ usr/share/roundcube/plugins/password/config.inc.php

+ var
+ var/lib

+ var/lib/samba
+ var/lib/samba/**

+ var/lib/redis
+ var/lib/redis/**
