#!/bin/sh

if [ "${1}" = "configure" ]; then
    if dpkg --compare-versions "${2}" lt "2.0.0"; then
        # Drop [backup] header from configs and remove -c parameter from cron
        sed -i '/\[backup\]/d' /etc/backup/*.conf
        sed -i 's/ -c / /g' /etc/cron.d/backup
    fi
    if dpkg --compare-versions "${2}" lt "2.3.0"; then
        # Convert partial, sparse and compress to extra-args
        for CONF in /etc/backup/*.conf; do
            EXTRA_ARGS=
            for OPT in partial sparse compress; do
                if grep -Eq "^[ \t]*${OPT}[ \t]+=[ \t]+(yes|true|1)" "${CONF}"; then
                    EXTRA_ARGS="${EXTRA_ARGS} --${OPT}"
                fi
                sed -Ei "/^[ \t]*${OPT}[ \t]+=/d" "${CONF}"
            done
            if [ -n "${EXTRA_ARGS}" ]; then
                echo "extra-args =${EXTRA_ARGS}" >>"${CONF}"
            fi
        done
    fi
fi
